version: "3"
    
services:
  db:
    image: mysql:5.7
    volumes:
      ## predefined volumes are not supported, hence a directory mapping is
      ## used.
      - ./db_data:/var/lib/mysql
    ports:
      ## explicitly set the ports, to make sure the service contains the port
      ## mapping as well.
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    labels:
      com.joyrex2001.kubedock.pull-policy: always
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
