name: CI

on:
  pull_request:

env:
  # Golang version to use across CI steps
  GOLANG_VERSION: '1.26.3'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Run unit tests
        run: make test