name: release
on:
  release:
    types:
      - published

env:
  # Golang version to use across CI steps
  GOLANG_VERSION: '1.25.3'
  
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Install dependencies
        run: make deps
      - name: Cross compile
        run: make gox
      - name: Archive builds
        run: |
          cd dist
          for r in *; do
            t=$(echo $r | sed 's/.exe$//')
            e="kubedock"
            [[ $r == *.exe ]] && e="kubedock.exe"
            mv $r $e
            tar czf $t.tar.gz $e
            rm $e
          done
      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${GITHUB_REF#refs/tags/} dist/*.tar.gz
